export type Language = 'pt' | 'es' | 'en';

export const languageOptions: { value: Language; short: string; label: string }[] = [
  { value: 'pt', short: 'PT', label: 'Português' },
  { value: 'es', short: 'ES', label: 'Español' },
  { value: 'en', short: 'EN', label: 'English' },
];

export const languageLocales: Record<Language, string> = {
  pt: 'pt-BR',
  es: 'es-ES',
  en: 'en-US',
};

export const translations = {
  pt: {
    enableDarkMode: 'Ativar modo noturno', enableLightMode: 'Ativar modo claro',
    language: 'Idioma', itinerary: 'MEU ROTEIRO', createMap: 'Criar mapa', switchTrip: 'Trocar mapa de viagem',
    mapsLive: 'Maps ao vivo', connecting: 'Conectando', synced: 'Sincronizado', syncError: 'Falha ao sincronizar', syncing: 'Sincronizando', signInGoogle: 'Entrar com Google', openAccount: 'Abrir conta de',
    mapTools: 'Ferramentas do mapa', searchMaps: 'Buscar no Google Maps', searchItinerary: 'Buscar no seu roteiro', searching: 'Buscando', clearSearch: 'Limpar busca', mapsResults: 'Resultados do Google Maps', saved: 'Salvo', noResults: 'Nenhum resultado encontrado.', filters: 'Filtros', filterPlaces: 'Filtrar lugares', showOnMap: 'Mostrar no mapa', onlyOpen: 'Somente abertos agora',
    yourItinerary: 'Seu roteiro em', firstItinerary: 'Crie seu primeiro roteiro', goodTime: 'Bom momento para explorar', planStop: 'Planeje a próxima parada', openSingular: 'aberto', openPlural: 'abertos', soon: 'em breve',
    emptyItinerary: 'Seu roteiro está vazio', emptyItineraryHint: 'Busque um lugar ou toque em um ponto do mapa.', addFromMaps: 'Adicionar pelo Google Maps', createFirstMap: 'Criar primeiro mapa', yourLocation: 'Sua localização', noPlaceFound: 'Nenhum lugar encontrado', removeFilters: 'Busque um lugar ou remova os filtros.', organizeTrip: 'Organize os locais da sua próxima viagem.', tapMapToAdd: 'Toque em um local do mapa para adicionar', loadingPlace: 'Carregando local…', zoomIn: 'Aumentar zoom', zoomOut: 'Diminuir zoom', centerLocation: 'Centralizar na minha localização', nearestFirst: 'Mais próximos primeiro', calculatingDistances: 'Calculando distâncias…', enableDistance: 'Ativar distância e ordenar', noPlaceItinerary: 'Nenhum lugar neste roteiro', returnMapHint: 'Volte ao mapa e use a busca para adicionar.',
    closeDetails: 'Fechar detalhes', photoOf: 'Foto de', photo: 'Foto', today: 'Hoje', pinColor: 'COR DO PIN', choosePinColor: 'Escolher cor do pin', automaticColor: 'Cor automática pelo horário', useAutomaticColor: 'Usar cor automática pelo horário', personalNote: 'NOTA PESSOAL', remove: 'Remover', goMaps: 'Ir com Maps', mainNavigation: 'Navegação principal', map: 'Mapa', list: 'Lista', newMap: 'Novo mapa',
    yourAccount: 'SUA CONTA', syncedItineraries: 'Roteiros sincronizados', enterRoamly: 'Entre no Easy Road Map', close: 'Fechar', cloudSaved: 'Tudo salvo na nuvem', couldNotSync: 'Não foi possível sincronizar', syncingItineraries: 'Sincronizando seus roteiros', linkedGoogle: 'Seus mapas ficam vinculados a esta Conta Google.', logout: 'Sair da conta', accessEverywhere: 'Acesse seus mapas e lugares salvos em qualquer dispositivo.', preparingLogin: 'Preparando login…', googleNotConfigured: 'O login do Google ainda não foi configurado neste ambiente.', googlePrivacy: 'O Easy Road Map recebe apenas seu nome, e-mail e identificação da Conta Google.',
    chooseTransport: 'Escolher meio de transporte', routeTo: 'ROTA PARA', leavingLocation: 'Saindo da sua localização', walk: 'A pé', car: 'Carro', bike: 'Bicicleta', transit: 'Transporte', openRoute: 'Abrir rota', routeOpensMaps: 'A rota será aberta no Google Maps.',
    removeFromItinerary: 'REMOVER DO ROTEIRO', removeQuestion: 'Remover', removeDescription: 'O local e a nota pessoal serão retirados deste mapa.', cancel: 'Cancelar', removePlace: 'Remover local', yourMaps: 'SEUS MAPAS', whereTo: 'Para onde vamos?', noMaps: 'Nenhum mapa criado', noMapsHint: 'Crie um destino abaixo para começar seu roteiro.', deleteMap: 'Excluir mapa', newDestination: 'NOVO DESTINO', destinationExample: 'Ex.: Roma', mapsPlace: 'LOCAL DO GOOGLE MAPS', addItinerary: 'Adicionar ao roteiro?', addMap: 'Adicionar ao mapa', deleteMapDescription: 'O mapa e todos os locais salvos nele serão removidos deste dispositivo.',
    openStatus: 'Aberto', soonStatus: 'Em breve', closedStatus: 'Fechado', distancePending: 'Calculando distância', noSavedPlace: 'Nenhum lugar salvo', savedPlace: 'lugar salvo', savedPlaces: 'lugares salvos', place: 'lugar', places: 'lugares',
    exploreNone: 'Confira os horários antes de sair.', openPlace: 'lugar aberto', openPlaces: 'lugares abertos', scheduleChange: 'com mudança de horário em breve.', visitNow: 'para visitar agora.',
    mapsLoading: 'Carregando Google Maps…', liveMap: 'MAPA AO VIVO', connectMaps: 'Conectar Google Maps', mapsKeyHelp: 'Use uma chave com Maps JavaScript API e Places API (New) habilitadas. Restrinja-a a este domínio.', pasteMapsKey: 'Cole sua chave do Google Maps', mapsKey: 'Chave do Google Maps', connect: 'Conectar', mapsKeyNote: 'A chave fica somente neste navegador. Para publicar sem esta etapa, configure-a no ambiente do site.', liveMapLabel: 'Mapa ao vivo do Google Maps', liveLocation: 'Sua localização ao vivo',
    green: 'Verde', yellow: 'Amarelo', red: 'Vermelho', blue: 'Azul', purple: 'Roxo',
  },
  es: {
    enableDarkMode: 'Activar modo nocturno', enableLightMode: 'Activar modo claro',
    language: 'Idioma', itinerary: 'MI ITINERARIO', createMap: 'Crear mapa', switchTrip: 'Cambiar mapa de viaje',
    mapsLive: 'Maps en vivo', connecting: 'Conectando', synced: 'Sincronizado', syncError: 'Error al sincronizar', syncing: 'Sincronizando', signInGoogle: 'Entrar con Google', openAccount: 'Abrir cuenta de',
    mapTools: 'Herramientas del mapa', searchMaps: 'Buscar en Google Maps', searchItinerary: 'Buscar en tu itinerario', searching: 'Buscando', clearSearch: 'Limpiar búsqueda', mapsResults: 'Resultados de Google Maps', saved: 'Guardado', noResults: 'No se encontraron resultados.', filters: 'Filtros', filterPlaces: 'Filtrar lugares', showOnMap: 'Mostrar en el mapa', onlyOpen: 'Solo abiertos ahora',
    yourItinerary: 'Tu itinerario en', firstItinerary: 'Crea tu primer itinerario', goodTime: 'Buen momento para explorar', planStop: 'Planifica la próxima parada', openSingular: 'abierto', openPlural: 'abiertos', soon: 'pronto',
    emptyItinerary: 'Tu itinerario está vacío', emptyItineraryHint: 'Busca un lugar o toca un punto del mapa.', addFromMaps: 'Añadir desde Google Maps', createFirstMap: 'Crear primer mapa', yourLocation: 'Tu ubicación', noPlaceFound: 'No se encontró ningún lugar', removeFilters: 'Busca un lugar o quita los filtros.', organizeTrip: 'Organiza los lugares de tu próximo viaje.', tapMapToAdd: 'Toca un lugar del mapa para añadirlo', loadingPlace: 'Cargando lugar…', zoomIn: 'Acercar', zoomOut: 'Alejar', centerLocation: 'Centrar en mi ubicación', nearestFirst: 'Más cercanos primero', calculatingDistances: 'Calculando distancias…', enableDistance: 'Activar distancia y ordenar', noPlaceItinerary: 'No hay lugares en este itinerario', returnMapHint: 'Vuelve al mapa y usa la búsqueda para añadir.',
    closeDetails: 'Cerrar detalles', photoOf: 'Foto de', photo: 'Foto', today: 'Hoy', pinColor: 'COLOR DEL PIN', choosePinColor: 'Elegir color del pin', automaticColor: 'Color automático según el horario', useAutomaticColor: 'Usar color automático según el horario', personalNote: 'NOTA PERSONAL', remove: 'Quitar', goMaps: 'Ir con Maps', mainNavigation: 'Navegación principal', map: 'Mapa', list: 'Lista', newMap: 'Nuevo mapa',
    yourAccount: 'TU CUENTA', syncedItineraries: 'Itinerarios sincronizados', enterRoamly: 'Entra en Easy Road Map', close: 'Cerrar', cloudSaved: 'Todo guardado en la nube', couldNotSync: 'No se pudo sincronizar', syncingItineraries: 'Sincronizando tus itinerarios', linkedGoogle: 'Tus mapas quedan vinculados a esta Cuenta de Google.', logout: 'Cerrar sesión', accessEverywhere: 'Accede a tus mapas y lugares guardados desde cualquier dispositivo.', preparingLogin: 'Preparando inicio de sesión…', googleNotConfigured: 'El inicio de sesión con Google aún no está configurado en este entorno.', googlePrivacy: 'Easy Road Map recibe únicamente tu nombre, correo e identificador de la Cuenta de Google.',
    chooseTransport: 'Elegir medio de transporte', routeTo: 'RUTA A', leavingLocation: 'Desde tu ubicación', walk: 'A pie', car: 'Coche', bike: 'Bicicleta', transit: 'Transporte público', openRoute: 'Abrir ruta', routeOpensMaps: 'La ruta se abrirá en Google Maps.',
    removeFromItinerary: 'QUITAR DEL ITINERARIO', removeQuestion: '¿Quitar', removeDescription: 'El lugar y la nota personal se eliminarán de este mapa.', cancel: 'Cancelar', removePlace: 'Quitar lugar', yourMaps: 'TUS MAPAS', whereTo: '¿A dónde vamos?', noMaps: 'No hay mapas creados', noMapsHint: 'Crea un destino abajo para empezar tu itinerario.', deleteMap: 'Eliminar mapa', newDestination: 'NUEVO DESTINO', destinationExample: 'Ej.: Roma', mapsPlace: 'LUGAR DE GOOGLE MAPS', addItinerary: '¿Añadir al itinerario?', addMap: 'Añadir al mapa', deleteMapDescription: 'El mapa y todos sus lugares guardados se eliminarán de este dispositivo.',
    openStatus: 'Abierto', soonStatus: 'Pronto', closedStatus: 'Cerrado', distancePending: 'Calculando distancia', noSavedPlace: 'Ningún lugar guardado', savedPlace: 'lugar guardado', savedPlaces: 'lugares guardados', place: 'lugar', places: 'lugares',
    exploreNone: 'Consulta los horarios antes de salir.', openPlace: 'lugar abierto', openPlaces: 'lugares abiertos', scheduleChange: 'con cambio de horario pronto.', visitNow: 'para visitar ahora.',
    mapsLoading: 'Cargando Google Maps…', liveMap: 'MAPA EN VIVO', connectMaps: 'Conectar Google Maps', mapsKeyHelp: 'Usa una clave con Maps JavaScript API y Places API (New) habilitadas. Restríngela a este dominio.', pasteMapsKey: 'Pega tu clave de Google Maps', mapsKey: 'Clave de Google Maps', connect: 'Conectar', mapsKeyNote: 'La clave queda solo en este navegador. Para publicar sin este paso, configúrala en el entorno del sitio.', liveMapLabel: 'Mapa en vivo de Google Maps', liveLocation: 'Tu ubicación en vivo',
    green: 'Verde', yellow: 'Amarillo', red: 'Rojo', blue: 'Azul', purple: 'Morado',
  },
  en: {
    enableDarkMode: 'Enable dark mode', enableLightMode: 'Enable light mode',
    language: 'Language', itinerary: 'MY ITINERARY', createMap: 'Create map', switchTrip: 'Switch trip map',
    mapsLive: 'Live Maps', connecting: 'Connecting', synced: 'Synced', syncError: 'Sync failed', syncing: 'Syncing', signInGoogle: 'Sign in with Google', openAccount: 'Open account for',
    mapTools: 'Map tools', searchMaps: 'Search Google Maps', searchItinerary: 'Search your itinerary', searching: 'Searching', clearSearch: 'Clear search', mapsResults: 'Google Maps results', saved: 'Saved', noResults: 'No results found.', filters: 'Filters', filterPlaces: 'Filter places', showOnMap: 'Show on map', onlyOpen: 'Open now only',
    yourItinerary: 'Your itinerary in', firstItinerary: 'Create your first itinerary', goodTime: 'A good time to explore', planStop: 'Plan your next stop', openSingular: 'open', openPlural: 'open', soon: 'soon',
    emptyItinerary: 'Your itinerary is empty', emptyItineraryHint: 'Search for a place or tap a point on the map.', addFromMaps: 'Add from Google Maps', createFirstMap: 'Create first map', yourLocation: 'Your location', noPlaceFound: 'No place found', removeFilters: 'Search for a place or remove the filters.', organizeTrip: 'Organize the places for your next trip.', tapMapToAdd: 'Tap a place on the map to add it', loadingPlace: 'Loading place…', zoomIn: 'Zoom in', zoomOut: 'Zoom out', centerLocation: 'Center on my location', nearestFirst: 'Nearest first', calculatingDistances: 'Calculating distances…', enableDistance: 'Enable distance and sort', noPlaceItinerary: 'No places in this itinerary', returnMapHint: 'Return to the map and use search to add one.',
    closeDetails: 'Close details', photoOf: 'Photo of', photo: 'Photo', today: 'Today', pinColor: 'PIN COLOR', choosePinColor: 'Choose pin color', automaticColor: 'Automatic color by opening hours', useAutomaticColor: 'Use automatic color by opening hours', personalNote: 'PERSONAL NOTE', remove: 'Remove', goMaps: 'Go with Maps', mainNavigation: 'Main navigation', map: 'Map', list: 'List', newMap: 'New map',
    yourAccount: 'YOUR ACCOUNT', syncedItineraries: 'Synced itineraries', enterRoamly: 'Sign in to Easy Road Map', close: 'Close', cloudSaved: 'Everything saved to the cloud', couldNotSync: 'Could not sync', syncingItineraries: 'Syncing your itineraries', linkedGoogle: 'Your maps are linked to this Google Account.', logout: 'Sign out', accessEverywhere: 'Access your saved maps and places on any device.', preparingLogin: 'Preparing sign-in…', googleNotConfigured: 'Google sign-in has not been configured in this environment yet.', googlePrivacy: 'Easy Road Map only receives your name, email, and Google Account identifier.',
    chooseTransport: 'Choose transportation', routeTo: 'ROUTE TO', leavingLocation: 'From your location', walk: 'Walk', car: 'Car', bike: 'Bicycle', transit: 'Public transit', openRoute: 'Open route', routeOpensMaps: 'The route will open in Google Maps.',
    removeFromItinerary: 'REMOVE FROM ITINERARY', removeQuestion: 'Remove', removeDescription: 'The place and personal note will be removed from this map.', cancel: 'Cancel', removePlace: 'Remove place', yourMaps: 'YOUR MAPS', whereTo: 'Where are we going?', noMaps: 'No maps created', noMapsHint: 'Create a destination below to start your itinerary.', deleteMap: 'Delete map', newDestination: 'NEW DESTINATION', destinationExample: 'E.g. Rome', mapsPlace: 'GOOGLE MAPS PLACE', addItinerary: 'Add to itinerary?', addMap: 'Add to map', deleteMapDescription: 'The map and all saved places in it will be removed from this device.',
    openStatus: 'Open', soonStatus: 'Soon', closedStatus: 'Closed', distancePending: 'Calculating distance', noSavedPlace: 'No saved places', savedPlace: 'saved place', savedPlaces: 'saved places', place: 'place', places: 'places',
    exploreNone: 'Check opening hours before leaving.', openPlace: 'open place', openPlaces: 'open places', scheduleChange: 'with an opening-hours change soon.', visitNow: 'to visit now.',
    mapsLoading: 'Loading Google Maps…', liveMap: 'LIVE MAP', connectMaps: 'Connect Google Maps', mapsKeyHelp: 'Use a key with Maps JavaScript API and Places API (New) enabled. Restrict it to this domain.', pasteMapsKey: 'Paste your Google Maps key', mapsKey: 'Google Maps key', connect: 'Connect', mapsKeyNote: 'The key stays only in this browser. To publish without this step, configure it in the site environment.', liveMapLabel: 'Live Google Maps map', liveLocation: 'Your live location',
    green: 'Green', yellow: 'Yellow', red: 'Red', blue: 'Blue', purple: 'Purple',
  },
} as const;

export type Copy = { [K in keyof typeof translations.pt]: string };

export function normalizeLanguage(value: string | null | undefined): Language {
  return value === 'es' || value === 'en' ? value : 'pt';
}
