import type { Language } from './i18n';

export const privacyContact = 'arthurmaquizito@gmail.com';

export const privacyCopy = {
  pt: {
    title: 'Privacidade e dados', close: 'Fechar', download: 'Baixar meus dados', downloading: 'Preparando arquivo…',
    exportHint: 'Baixe um arquivo JSON com seus roteiros, dados da conta e preferências. Com login, ele inclui a cópia na nuvem e as alterações presentes neste navegador.',
    deleteAccount: 'Excluir minha conta e meus roteiros', deleteLocal: 'Apagar roteiros deste navegador',
    confirmTitle: 'Excluir os dados do Easy Road Map?', confirm: 'Confirmar exclusão', cancel: 'Cancelar', deleting: 'Excluindo…',
    confirmAccount: 'Isso remove sua conta do app, seus roteiros na nuvem e todos os convites de compartilhamento, limpa o cache desta conta neste navegador e encerra suas sessões. Sua Conta Google continua existindo. Esta ação não pode ser desfeita; baixe seus dados antes, se desejar.',
    confirmLocal: 'Isso apaga os roteiros e notas de visitante deste navegador. Não altera dados de contas conectadas nem cópias em outros aparelhos. Esta ação não pode ser desfeita.',
    deleted: 'Seus dados foram excluídos.', failure: 'Não foi possível concluir. Verifique a conexão e tente novamente.',
    locationTitle: 'Usar sua localização?', locationOn: 'Localização ativada nesta sessão', locationOff: 'Localização desativada',
    locationHelp: 'Ela mostra o ponto azul e ordena os locais por distância enquanto você usa o app. As coordenadas podem ser enviadas ao Google para mapas e buscas, mas não são gravadas nos seus roteiros. Você pode continuar sem permitir.',
    enable: 'Usar localização', disable: 'Parar localização', later: 'Continuar sem localização',
    locationHint: 'Você pode parar o acompanhamento aqui. Para revogar a permissão do site, use as configurações do navegador.',
    sections: [
      ['O que guardamos', 'Seus mapas, locais salvos, notas e cores dos pins. Também guardamos referências e informações dos lugares, como endereço, horários e links de fotos. As distâncias são calculadas no momento e não são incluídas nos novos salvamentos.'],
      ['No aparelho e na nuvem', 'Sem login, os roteiros ficam somente neste navegador e podem ser perdidos ao limpar seus dados. Com Google, os roteiros são enviados ao banco Cloudflare D1 da hospedagem Sites e também mantidos em cache neste navegador, separados por conta. Tema e idioma ficam neste aparelho.'],
      ['Acesso ao app', 'A página do app é acessível publicamente para que convidados possam abrir seus convites. Isso não torna seus roteiros públicos: seus mapas sincronizados exigem login e só aparecem para sua conta ou para e-mails convidados por você.'],
      ['Login e serviços externos', 'O Google informa seu identificador, nome, e-mail e, quando disponível, foto de perfil. A sessão usa um cookie com duração de até 7 dias. Google Maps e Places recebem consultas e dados necessários para mostrar mapas e lugares. Rotas abertas no Google Maps seguem também as regras desse serviço.'],
      ['Compartilhamento', 'Quando você convida alguém para um mapa, guardamos o e-mail convidado e o identificador do convite. Somente uma sessão Google com esse mesmo e-mail pode ver os locais do mapa. Notas pessoais não são exibidas. O convite pode ser revogado a qualquer momento.'],
      ['Por quanto tempo', 'Os roteiros na nuvem permanecem até você removê-los ou excluir sua conta do app. Os dados locais permanecem até sua limpeza. A exclusão retira os registros ativos da conta e invalida as sessões; ela não remove arquivos que você já baixou. Cópias em aparelhos desconectados não podem ser apagadas remotamente e são descartadas ao entrar novamente com uma nova conta do app. Backups técnicos da hospedagem podem manter cópias temporárias; fale conosco para informações sobre esses prazos.'],
      ['Seu controle', 'Use os botões acima para acessar e baixar seus dados ou excluí-los. Você pode corrigir mapas e notas no próprio roteiro. Para dúvidas, correção de dados de identificação ou outros pedidos de privacidade, entre em contato pelo e-mail abaixo.'],
    ],
    contact: 'Responsável pelo app e contato de privacidade', googlePolicy: 'Privacidade do Google', cloudflarePolicy: 'Privacidade da Cloudflare',
  },
  es: {
    title: 'Privacidad y datos', close: 'Cerrar', download: 'Descargar mis datos', downloading: 'Preparando archivo…',
    exportHint: 'Descarga un archivo JSON con tus itinerarios, datos de cuenta y preferencias. Con sesión iniciada, incluye la copia en la nube y los cambios de este navegador.',
    deleteAccount: 'Eliminar mi cuenta e itinerarios', deleteLocal: 'Borrar itinerarios de este navegador',
    confirmTitle: '¿Eliminar los datos de Easy Road Map?', confirm: 'Confirmar eliminación', cancel: 'Cancelar', deleting: 'Eliminando…',
    confirmAccount: 'Se eliminarán tu cuenta de la app, todos tus itinerarios de la nube y todas las invitaciones para compartir; también se limpiará la caché de esta cuenta en este navegador y se cerrarán tus sesiones. Tu Cuenta de Google seguirá existiendo. Esta acción no se puede deshacer; descarga tus datos antes si lo deseas.',
    confirmLocal: 'Se borrarán los itinerarios y notas de visitante de este navegador. No afecta a cuentas conectadas ni a otros dispositivos. Esta acción no se puede deshacer.',
    deleted: 'Tus datos se han eliminado.', failure: 'No se pudo completar. Comprueba tu conexión e inténtalo de nuevo.',
    locationTitle: '¿Usar tu ubicación?', locationOn: 'Ubicación activa en esta sesión', locationOff: 'Ubicación desactivada',
    locationHelp: 'Permite mostrar el punto azul y ordenar lugares por distancia mientras usas la app. Las coordenadas pueden enviarse a Google para mapas y búsquedas, pero no se guardan en tus itinerarios. Puedes continuar sin permitirlo.',
    enable: 'Usar ubicación', disable: 'Detener ubicación', later: 'Continuar sin ubicación',
    locationHint: 'Puedes detener el seguimiento aquí. Para revocar el permiso del sitio, usa los ajustes del navegador.',
    sections: [
      ['Qué guardamos', 'Tus mapas, lugares, notas y colores de los marcadores. También referencias e información de los lugares, como dirección, horarios y enlaces de fotos. Las distancias se calculan al momento y no se incluyen en los nuevos guardados.'],
      ['En el dispositivo y la nube', 'Sin sesión, los itinerarios solo están en este navegador y pueden perderse al borrar sus datos. Con Google, se envían a Cloudflare D1 en el alojamiento Sites y se guardan en caché, separados por cuenta. El tema y el idioma permanecen en este dispositivo.'],
      ['Acceso a la app', 'La página de la app es pública para que las personas invitadas puedan abrir sus invitaciones. Esto no hace públicos tus itinerarios: los mapas sincronizados requieren iniciar sesión y solo son visibles para tu cuenta o para los correos que invites.'],
      ['Inicio de sesión y terceros', 'Google proporciona tu identificador, nombre, correo y, si está disponible, foto de perfil. La sesión usa una cookie de hasta 7 días. Google Maps y Places reciben las consultas y datos necesarios para mostrar mapas y lugares. Las rutas abiertas en Google Maps también siguen las reglas de ese servicio.'],
      ['Compartir', 'Al invitar a alguien a un mapa, guardamos el correo invitado y el identificador de la invitación. Solo una sesión de Google con ese mismo correo puede ver los lugares del mapa. No se muestran las notas personales. Puedes revocar la invitación en cualquier momento.'],
      ['Plazos de conservación', 'Los itinerarios de la nube permanecen hasta que los quites o elimines tu cuenta de la app. Los datos locales permanecen hasta su limpieza. El borrado elimina registros activos e invalida sesiones, pero no archivos ya descargados. No se pueden borrar remotamente copias en dispositivos desconectados; se descartan al volver a iniciar sesión con una cuenta nueva de la app. Las copias técnicas de seguridad del alojamiento pueden conservar datos temporalmente; contáctanos para consultar estos plazos.'],
      ['Tus opciones', 'Usa los botones anteriores para acceder, descargar o eliminar tus datos. Puedes corregir mapas y notas en el itinerario. Para consultas, correcciones de datos de identificación u otras solicitudes de privacidad, escribe al correo de abajo.'],
    ],
    contact: 'Responsable de la app y contacto de privacidad', googlePolicy: 'Privacidad de Google', cloudflarePolicy: 'Privacidad de Cloudflare',
  },
  en: {
    title: 'Privacy and data', close: 'Close', download: 'Download my data', downloading: 'Preparing file…',
    exportHint: 'Download a JSON file with your itineraries, account details and preferences. When signed in, it includes your cloud copy and the changes in this browser.',
    deleteAccount: 'Delete my account and itineraries', deleteLocal: 'Clear this browser’s itineraries',
    confirmTitle: 'Delete your Easy Road Map data?', confirm: 'Confirm deletion', cancel: 'Cancel', deleting: 'Deleting…',
    confirmAccount: 'This removes your app account, all cloud itineraries and all sharing invitations, clears this account’s cache in this browser and ends your sessions. Your Google Account remains. This cannot be undone; download your data first if you want a copy.',
    confirmLocal: 'This deletes guest itineraries and notes from this browser. It does not affect signed-in accounts or other devices. This cannot be undone.',
    deleted: 'Your data has been deleted.', failure: 'Could not complete this action. Check your connection and try again.',
    locationTitle: 'Use your location?', locationOn: 'Location enabled for this session', locationOff: 'Location disabled',
    locationHelp: 'It shows the blue dot and sorts places by distance while you use the app. Coordinates may be sent to Google for maps and searches, but are not stored in your itineraries. You can continue without allowing it.',
    enable: 'Use location', disable: 'Stop location', later: 'Continue without location',
    locationHint: 'You can stop tracking here. To revoke this site’s permission, use your browser settings.',
    sections: [
      ['What we store', 'Your maps, saved places, notes and pin colors. We also store place references and information such as addresses, opening hours and photo links. Distances are calculated live and are not included in new saves.'],
      ['On your device and in the cloud', 'Without sign-in, itineraries stay in this browser and can be lost when its data is cleared. With Google sign-in, they are sent to Cloudflare D1 through Sites hosting and also cached in this browser, separately for each account. Theme and language stay on this device.'],
      ['App access', 'The app page is publicly reachable so invited people can open their invitations. This does not make your itineraries public: synced maps require sign-in and are visible only to your account or the email addresses you invite.'],
      ['Sign-in and external services', 'Google provides your identifier, name, email and profile picture when available. The session uses a cookie lasting up to 7 days. Google Maps and Places receive queries and data needed to display maps and places. Routes opened in Google Maps also follow that service’s rules.'],
      ['Sharing', 'When you invite someone to a map, we store the invited email and an invitation identifier. Only a Google session with that exact email can view the map’s places. Personal notes are not shown. You can revoke an invitation at any time.'],
      ['How long data stays', 'Cloud itineraries remain until you remove them or delete your app account. Local data stays until cleared. Deletion removes active account records and invalidates sessions; it does not remove files you already downloaded. Offline device copies cannot be erased remotely; they are discarded when signing in again with a new app account. Hosting backups may temporarily retain copies; contact us for information about these periods.'],
      ['Your controls', 'Use the buttons above to access, download or delete your data. You can correct maps and notes in the itinerary itself. For questions, identity corrections or other privacy requests, contact the email below.'],
    ],
    contact: 'App operator and privacy contact', googlePolicy: 'Google privacy', cloudflarePolicy: 'Cloudflare privacy',
  },
} satisfies Record<Language, unknown>;
